### ISSUE TITLE
Automatic form submission

### ISSUE THREAD

**Issue by wassimbj** [wassimbj/searchgpt#1]
The form is not submitted due a bug in reactjs [here](https://github.com/facebook/react/issues/10135#issuecomment-314441175)
i will fix it soon

**Comment by SteveRyherd** [comment]
Did you get this working / did you happen to see which version of React ChatGPT is using?

**Comment by wassimbj** [comment]
Hey steve,
Yes this is fixed in this [commit](https://github.com/wassimbj/searchgpt/commit/ed402b6b1fd65ff7edabc37db4e745621e353ebc)
Its not about chatgpt react version, but as i faced this issue i had to google it see whats wrong exactly and i found that link i provided above

**Comment by wassimbj** [comment]
If you have this issue, just download the code again
